[Proxy]
VM-01 = vmess, v30.hdacd.com, 30830, username=cbb3f877-d1fb-344c-87a9-d153bffd5484, tls=false, vmess-aead=true, ws=false, ws-path=/, sni=v30.hdacd.com, ws-headers=Host:v30.hdacd.com, skip-cert-verify=false, udp=false
VM-02 = vmess, v12.hdacd.com, 30812, username=cbb3f877-d1fb-344c-87a9-d153bffd5484, tls=false, vmess-aead=true, ws=false, ws-path=/, sni=v12.hdacd.com, ws-headers=Host:v12.hdacd.com, skip-cert-verify=false, udp=false
